### ISSUE TITLE
go-bs-autobatch can't be built due to undefined blockstore.ErrNotFound

### ISSUE THREAD

**Issue by fbac** [application-research/go-bs-autobatch#2]
go-bs-autobatch can't be built due to undefined blockstore.ErrNotFound functions called:

```bash
# github.com/application-research/go-bs-autobatch
../../../go/pkg/mod/github.com/application-research/go-bs-autobatch@v0.0.0-20211215020302-c4c0b68ef402/autobatch.go:216:34: undefined: blockstore.ErrNotFound
../../../go/pkg/mod/github.com/application-research/go-bs-autobatch@v0.0.0-20211215020302-c4c0b68ef402/autobatch.go:238:34: undefined: blockstore.ErrNotFound
../../../go/pkg/mod/github.com/application-research/go-bs-autobatch@v0.0.0-20211215020302-c4c0b68ef402/autobatch.go:395:33: undefined: blockstore.ErrNotFound
```

**Additional context**
blockstore changed its way to raise ErrNotFound since [this PR](https://github.com/ipfs/go-ipfs-blockstore/pull/48), which breaks compatibility.

The logic should be changed to use ipld.ErrNotFound instead of blockstore.ErrNotFound.

**Comment by alvin-reyes** [comment]
Resolved by the latest release here

https://github.com/application-research/go-bs-autobatch/releases/tag/v0.1.0
